kind: Deployment
apiVersion: apps/v1
metadata:
  name: storedata
spec:
  replicas: 3
  selector:
    matchLabels:
      name: store
  template:
    metadata:
      name: mypod
      labels:
        name: store
    spec:
      containers:
        - name: c00
          image: rehan2020/storedataapiimage
          ports:
            - containerPort: 8082
